package br.com.artheus.matchhire.mapper;

import br.com.artheus.matchhire.domain.model.Candidate;
import br.com.artheus.matchhire.dto.CandidateRequestDTO;
import br.com.artheus.matchhire.dto.CandidateResponseDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface CandidateMapper {

    /**
     * Converts CandidateRequestDTO to Candidate entity.
     * PublicId will be generated by entity's @PrePersist.
     */
    Candidate toEntity(CandidateRequestDTO dto);

    /**
     * Converts Candidate entity to CandidateResponseDTO.
     */
    @Mapping(source = "id", target = "publicId") // publicId as UUID in DTO
    CandidateResponseDTO toResponseDTO(Candidate candidate);
}
