package br.com.artheus.matchhire.mapper;

import br.com.artheus.matchhire.domain.model.Company;
import br.com.artheus.matchhire.dto.CompanyRequestDTO;
import br.com.artheus.matchhire.dto.CompanyResponseDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

/**
 * Mapper for converting between Company entities and DTOs.
 */
@Mapper(componentModel = "spring")
public interface CompanyMapper {

    /**
     * Maps a CompanyRequestDTO to a Company entity.
     * Some fields are ignored because they are managed automatically or via relationships.
     */
    @Mappings({
            @Mapping(target = "id", ignore = true) // Ignored because it's auto-generated by the database
            ,
            @Mapping(target = "jobs", ignore = true) // Ignored because jobs are linked in the service layer
            ,
            @Mapping(target = "publicId", ignore = true) // Ignored because it's automatically generated in @PrePersist
            ,
            @Mapping(target = "active", ignore = true) // Ignored because it has a default initialization value
    })
    Company toEntity(CompanyRequestDTO dto);

    /**
     * Maps a Company entity to a CompanyResponseDTO.
     */
    @Mapping(source = "publicId", target = "publicId")
    CompanyResponseDTO toResponseDTO(Company company);
}
