package br.com.artheus.matchhire.mapper;

import br.com.artheus.matchhire.domain.model.Job;
import br.com.artheus.matchhire.dto.JobRequestDTO;
import br.com.artheus.matchhire.dto.JobResponseDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

/**
 * Mapper for converting between Job entities and DTOs.
 */
@Mapper(componentModel = "spring")
public interface JobMapper {

    /**
     * Converts JobRequestDTO to Job entity.
     * Some fields are ignored because they are handled by the system or set in the service layer.
     */
    @Mappings({
            @Mapping(target = "id", ignore = true) // Ignored because it's auto-generated by the database
            ,
            @Mapping(target = "publicId", ignore = true) // Ignored because it's automatically generated in @PrePersist
            ,
            @Mapping(target = "company", ignore = true) // Ignored because it's set manually in the service layer using companyId
            ,
            @Mapping(target = "applications", ignore = true) // Ignored because applications are managed in the service layer
            ,
            @Mapping(target = "active", ignore = true) // Ignored because it has a default initialization value
    })
    Job toEntity(JobRequestDTO dto);

    /**
     * Converts Job entity to JobResponseDTO.
     */
    @Mappings({
            @Mapping(source = "company.id", target = "companyId"),
            @Mapping(source = "company.name", target = "companyName")
    })
    JobResponseDTO toResponseDTO(Job job);
}
